---
title: "R4epi6.8"
author: "hirbo"
date: "2026-01-20"
output: html_document
---
# Subsetting Data Frame
```{r}
library(dplyr)
```
```{r}
set.seed(123)

drug_trial <- tibble(
  # Follow-up year, 0 = baseline, 1 = year one, 2 = year two.
  year = rep(0:2, times = 20),
  # Participant age a baseline. Must be between the ages of 35 and 75 at 
  # baseline to be eligible for the study
  age = sample(35:75, 20, TRUE) %>% rep(each = 3),
  # Drug the participant received, Placebo or active
  drug = sample(c("Placebo", "Active"), 20, TRUE) %>% 
    rep(each = 3),
  # Reported headaches side effect, Y/N
  se_headache = if_else(
    drug == "Placebo", 
    sample(0:1, 60, TRUE, c(.95,.05)), 
    sample(0:1, 60, TRUE, c(.10, .90))
  ),
  # Report diarrhea side effect, Y/N
  se_diarrhea = if_else(
    drug == "Placebo", 
    sample(0:1, 60, TRUE, c(.98,.02)), 
    sample(0:1, 60, TRUE, c(.20, .80))
  ),
  # Report dry mouth side effect, Y/N
  se_dry_mouth = if_else(
    drug == "Placebo", 
    sample(0:1, 60, TRUE, c(.97,.03)), 
    sample(0:1, 60, TRUE, c(.30, .70))
  ),
  # Participant had myocardial infarction in study year, Y/N
  mi = if_else(
    drug == "Placebo", 
    sample(0:1, 60, TRUE, c(.85, .15)), 
    sample(0:1, 60, TRUE, c(.80, .20))
  )
)
```
```{r}
drug_trial
```
```{r}
drug_trial <- drug_trial %>%
  mutate(
    #student id, there are 20 people enrolled in the trial.
    id = rep( 1:20, each = 3)
  ) %>%
  print()
```
```{r}
drug_trial %>%
  select(id, year, age, se_headache,se_diarrhea,se_dry_mouth,mi)
```
```{r}
drug_trial <- drug_trial %>%
  select(id, everything()) %>%
  print()
```
```{r}
drug_trial <- drug_trial %>%
  mutate(age_center = age - mean(age)) %>%
  print()
```
```{r}
drug_trial %>%
  select(age, age_center)
```
```{r}
drug_trial %>%
  select(id, year, starts_with("se"))
```
```{r}
nhanes <- tibble(
  SEQN = c(1:4),
  ALQ101 = c(1, 2, 1, 2),
  ALQ110 = c(2,2,2,1),
) %>%
  print()
```
```{r}
nhanes %>%
  rename(
    id = SEQN,
    drinks_12_year = ALQ101,
    drinks_12_life = ALQ110
  )
```
```{r}
nhanes %>%
  rename_with(tolower)
```
```{r}
drug_trial %>%
  slice(1:5)
```
