---
title: "Survival Analysis practice"
author: "hirbo"
date: "2026-01-12"
output: html_document
---
# survival analysis
```{r}
install.packages("survival", type = "binary")
```
```{r}
library(survival)
```
## load lung cancer dataset
```{r}
data("lung")
head(lung)
str(lung)
summary(lung)
```
#prepare data
##recode status; 1=censored,2=dead ->
0=censored, 1=event
```{r}
lung$status2 <- ifelse(lung$status ==2, 1, 0)
lung$sex <- factor(lung$sex, labels = c("male", "female"))
```
```{r}
library(survminer)
```
#kaplan meier survival curve by sex
```{r}
km_fit <- survfit(Surv(time, status2) ~ sex, data =lung)
ggsurvplot(km_fit,
           data = lung,
           pval = TRUE,
           risk.table =TRUE,
           conf.int =TRUE,
           xlab = "time (days)" ,
           ylab = "survival probability",
           title = "Kaplan Meier Survival by sex",
           legend.tittle = "sex")
```
#read median survival
```{r}
summary(km_fit)$table
```